
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int agregarEstados = 17;
  public static final int union = 21;
  public static final int reverso = 26;
  public static final int ERaAFD = 25;
  public static final int agregarAlfabeto = 18;
  public static final int coma = 2;
  public static final int minimizacion = 30;
  public static final int cpar = 6;
  public static final int or = 9;
  public static final int cero_o_uno = 10;
  public static final int cero_o_mas = 8;
  public static final int EstadoFinal = 28;
  public static final int EstadoInicial = 27;
  public static final int punto = 3;
  public static final int AFND = 16;
  public static final int EOF = 0;
  public static final int agregarexpresion = 31;
  public static final int agregarTransicion = 19;
  public static final int id = 34;
  public static final int DEF = 13;
  public static final int MAIN = 11;
  public static final int AF = 14;
  public static final int puntocoma = 4;
  public static final int uno_o_mas = 7;
  public static final int error = 1;
  public static final int ER = 15;
  public static final int graficar = 29;
  public static final int ERaAFND = 24;
  public static final int interseccion = 22;
  public static final int cerradura = 33;
  public static final int concatenacion = 32;
  public static final int FIN = 12;
  public static final int diferencia = 23;
  public static final int complemento = 20;
  public static final int apar = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "coma",
  "punto",
  "puntocoma",
  "apar",
  "cpar",
  "uno_o_mas",
  "cero_o_mas",
  "or",
  "cero_o_uno",
  "MAIN",
  "FIN",
  "DEF",
  "AF",
  "ER",
  "AFND",
  "agregarEstados",
  "agregarAlfabeto",
  "agregarTransicion",
  "complemento",
  "union",
  "interseccion",
  "diferencia",
  "ERaAFND",
  "ERaAFD",
  "reverso",
  "EstadoInicial",
  "EstadoFinal",
  "graficar",
  "minimizacion",
  "agregarexpresion",
  "concatenacion",
  "cerradura",
  "id"
  };
}

